[package]
name = "pyrus-nn"
version = "0.1.0"
authors = ["Miles Granger <miles59923@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "^0.12"
ndarray-rand = "^0.9"
ndarray-parallel = "^0.9"
rand = "^0.6"
